# display

set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windows

setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed

set -g set-titles on          # set terminal title

set -g display-panes-time 800 # slightly longer pane indicators display time
set -g display-time 1000      # slightly longer status messages display time

# activity
set -g monitor-activity on
set -g visual-activity off

bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"

# splitting panes

bind _ split-pane -h
bind - split-pane -v

# pane resizing
bind = resize-pane -x 50% -y 50%
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

# enable mouse support for switching panes/windows
#set -g mouse-utf8 on
set -g mouse on

# window movement
unbind p
unbind n
bind -r C-l next-window
bind -r C-h previous-window

# copy

bind Enter copy-mode # enter copy mode
setw -g mode-keys vi
unbind -T copy-mode-vi v
unbind -T copy-mode-vi y
bind -Tcopy-mode-vi v send-keys -X begin-selection
bind -Tcopy-mode-vi C-j               send -X copy-pipe-and-cancel 'pbcopy'
bind -Tcopy-mode-vi Enter             send -X copy-pipe-and-cancel 'pbcopy'
bind -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'pbcopy'
bind -Tcopy-mode-vi y send -X copy-pipe-and-cancel 'pbcopy'
